server.port: 8086

services.identity.uri.internal: http://gaia-x.identity.local:8081/demo/api/identity/user-account

spring.datasource.url: jdbc:postgresql://${PSQL_DB_HOST}:${PSQL_DB_PORT}/${PSQL_DB_DS}
spring.datasource.username: ${PSQL_DB_USERNAME}
spring.datasource.password: ${PSQL_DB_PASSWORD}
spring.datasource.driver-class-name: org.postgresql.Driver

spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
spring.jpa.database: POSTGRESQL
spring.main.allow-circular-references: true

# KEYCLOAK-------------------------------------------
keycloak.auth-server-url: ${KC_URL}
keycloak.realm: ${KC_REALM}
keycloak.resource: ${KC_RESOURCE}
keycloak.public-client: true
keycloak.bearer-only: true

keycloak.principal-attribute: preferred_username

check-keycloak-token: true
#----------------------------------------------------

springfox:
  documentation:
    swaggerUi:
      baseUrl: /api/account
    openApi:
      v3:
        path: /api/account/v3/api-docs
    swagger:
      v2:
        path: /api/account/v2/api-docs
---
spring.config.activate.on-profile: mesh
server.port: 80
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s
management.endpoint.health.probes.enabled: true
management.endpoints.web.exposure.include: "*"
management.server.port: 4004
services.identity.uri.internal: http://demo/demo/api/identity/user-account
